// Uploads a file directly to Cloudinary using a signature generated by
// the backend (see postController.createImageUploadSignature /
// createVideoUploadSignature). The signature is an HMAC of the upload
// params + timestamp using the API secret, which never leaves the server.
// Cloudinary validates the signature before accepting the upload.

// Uploads a single file to Cloudinary. `signatureData` is the object
// returned by the backend's signature endpoints. Returns the Cloudinary
// JSON response (contains secure_url, public_id, etc).
export const uploadToCloudinary = async ({ file, signatureData }) => {
  const {
    cloudName,
    apiKey,
    timestamp,
    signature,
    folder,
    resourceType = "image",
    transformation,
    eager,
    eagerAsync,
    notificationUrl,
    context,
  } = signatureData;

  const formData = new FormData();
  formData.append("file", file);
  formData.append("api_key", apiKey);
  formData.append("timestamp", String(timestamp));
  formData.append("signature", signature);
  formData.append("folder", folder);

  if (transformation) {
    formData.append("transformation", transformation);
  }
  if (eager) {
    formData.append("eager", eager);
  }
  if (eagerAsync) {
    formData.append("eager_async", "true");
  }
  if (notificationUrl) {
    formData.append("notification_url", notificationUrl);
  }
  if (context) {
    formData.append("context", context);
  }

  const url = `https://api.cloudinary.com/v1_1/${cloudName}/${resourceType}/upload`;

  const res = await fetch(url, {
    method: "POST",
    body: formData,
  });

  if (!res.ok) {
    let message = `Cloudinary upload failed (${res.status})`;
    try {
      const data = await res.json();
      message = data?.error?.message || message;
    } catch {
      // ignore parse error, use default message
    }
    const err = new Error(message);
    err.code = "CLOUDINARY_UPLOAD_FAILED";
    throw err;
  }

  return res.json();
};
